version: ~> 1.0

os: linux
dist: xenial

language: scala

scala:
  - "2.12.10" # not used for anything but still needed to have sbt available

sudo: false

before_install:
  # make comparing to origin/master work
  - git remote set-branches --add origin master && git fetch
  - whereis java
  - java -version
  # Initialize launcher from the correct URL so that later sbt runs work out of the box.
  # Travis' default sbt launch script refers to `repo.scala-sbt.org` for downloading the launcher
  # which currently doesn't work any more
  - sbt -sbt-launch-repo https://repo1.maven.org/maven2 exit

addons:
  apt:
    sources:
      # Official debian package for AdoptOpenJDK from https://adoptopenjdk.net/installation.html#linux-pkg
      - sourceline: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ xenial main
        key_url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    packages:
      - graphviz
      - adoptopenjdk-8-hotspot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64
    - PATH=/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin:$PATH
    # override default (release to maven central) to only close and go to staging repo
    - CI_SONATYPE_RELEASE="; sonatypePrepare; sonatypeBundleUpload; sonatypeClose"

script:
  - sbt -jvm-opts .jvmopts-travis "$CMD"

jobs:
  include:
    - stage: mima
      env: CMD="+mimaReportBinaryIssues"
    - stage: whitesource
      script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt whitesourceCheckPolicies whitesourceUpdate
    - stage: publish
      env: CMD="ci-release"
      name: artifacts to bintray

stages:
  - name: mima

  - name: whitesource
    if: repo=akka/akka-http AND ( ( branch = master AND type = push ) OR tag =~ ^v )

  - name: publish
    if: repo=akka/akka-http AND ( ( (branch = master OR branch = release-10.1) AND type = push ) OR tag =~ ^v )
