version: ~> 1.0

language: scala

scala:
  - "2.12.13" # not used for anything but still needed to have sbt available

git:
  depth: 500 # to make sure we have enough depth to power git describe for sbt-dynver (used for snapshot version numbers)

before_install:
  # make comparing to origin/master work
  - git remote set-branches --add origin master && git fetch
  # using jabba for custom jdk management
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.1/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install adopt@1.8-0
  - jabba use "adopt@1.8-0"
  - java -version

addons:
  apt:
    packages:
    - graphviz

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.jabba/jdk
    - $HOME/.cache/coursier

script:
  - sbt -jvm-opts .jvmopts-travis "$CMD"

jobs:
  include:
    - stage: mima
      env: CMD="+mimaReportBinaryIssues"
    - stage: whitesource
      script: git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH" && sbt whitesourceCheckPolicies whitesourceUpdate
    - stage: publish
      env: CMD="+publish"
      name: artifacts to bintray
    - script: eval "$(ssh-agent -s)" && echo $SCP_SECRET | base64 -d > /tmp/id_rsa && chmod 600 /tmp/id_rsa && ssh-add /tmp/id_rsa && sbt -jvm-opts .jvmopts-travis -Dakka.genjavadoc.enabled=true publishRsync
      name: paradox and api docs to gustav

stages:
  - name: mima
    if: repo=akka/akka-http AND ( ( branch = master AND type = push ) OR tag =~ ^v )

  - name: whitesource
    if: repo=akka/akka-http AND ( ( branch = master AND type = push ) OR tag =~ ^v )

  - name: publish
    if: repo=akka/akka-http AND ( ( branch = master AND type = push ) OR tag =~ ^v )
